#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.1
#  in conjunction with Tcl version 8.6
#    Apr 21, 2020 12:06:36 PM CEST  platform: Windows NT

import sys

from src.gui import ga_gui_support

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    ga_gui_support.set_Tk_var()
    top = Toplevel1 (root)
    ga_gui_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    ga_gui_support.set_Tk_var()
    top = Toplevel1 (w)
    ga_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1293x695+-8+0")
        top.minsize(148, 1)
        top.maxsize(4484, 1061)
        top.resizable(1, 1)
        top.title("Super-hiper Optimizer v1.0")
        top.configure(borderwidth="2")
        top.configure(background="#404040")
        top.configure(highlightbackground="#f0f0f0f0f0f0")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.26, rely=0.024, height=48, width=561)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#cab957")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(compound='center')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 16 -weight bold -slant italic")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(relief="groove")
        self.Label1.configure(text='''~~~~~ Super-Hiper Optimizer ~~~~~''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.012, rely=0.122, relheight=0.859
                , relwidth=0.974)
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#376c6c")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.01, rely=0.117, relheight=0.864, relwidth=0.487)

        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="1")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#595959")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Frame4 = tk.Frame(self.Frame2)
        self.Frame4.place(relx=0.021, rely=0.021, relheight=0.203
                , relwidth=0.958)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="1")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#316060")
        self.Frame4.configure(highlightbackground="#d9d9d9")
        self.Frame4.configure(highlightcolor="black")

        self.Label4 = tk.Label(self.Frame4)
        self.Label4.place(relx=0.022, rely=0.01, height=34, width=315)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#316060")
        self.Label4.configure(borderwidth="0")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 12")
        self.Label4.configure(foreground="#fdfd00")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Function''')

        self.Label5 = tk.Label(self.Frame4)
        self.Label5.place(relx=0.571, rely=0.01, height=33, width=199)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#316060")
        self.Label5.configure(borderwidth="0")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Segoe UI} -size 12")
        self.Label5.configure(foreground="#fdfd00")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="white")
        self.Label5.configure(text='''argument domain''')

        self.Label6 = tk.Label(self.Frame4)
        self.Label6.place(relx=0.593, rely=0.4, height=20, width=44)
        self.Label6.configure(activebackground="#316060")
        self.Label6.configure(activeforeground="white")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#316060")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Segoe UI} -size 12")
        self.Label6.configure(foreground="#adf0f5")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''x1 :''')

        self.Label7 = tk.Label(self.Frame4)
        self.Label7.place(relx=0.593, rely=0.667, height=21, width=44)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#316060")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="-family {Segoe UI} -size 12")
        self.Label7.configure(foreground="#adf0f5")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''x2 :''')

        self.Entry1 = tk.Entry(self.Frame4)
        self.Entry1.place(relx=0.681, rely=0.4,height=20, relwidth=0.143)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Entry2 = tk.Entry(self.Frame4)
        self.Entry2.place(relx=0.681, rely=0.667,height=20, relwidth=0.143)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Spinbox1_10 = tk.Spinbox(self.Frame4, from_=1.0, to=100.0)
        self.Spinbox1_10.place(relx=0.111, rely=0.448, relheight=0.21
                , relwidth=0.385)
        self.Spinbox1_10.configure(activebackground="#f9f9f9")
        self.Spinbox1_10.configure(background="white")
        self.Spinbox1_10.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_10.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_10.configure(font="TkDefaultFont")
        self.Spinbox1_10.configure(foreground="black")
        self.Spinbox1_10.configure(highlightbackground="black")
        self.Spinbox1_10.configure(highlightcolor="black")
        self.Spinbox1_10.configure(insertbackground="black")
        self.Spinbox1_10.configure(selectbackground="#c4c4c4")
        self.Spinbox1_10.configure(selectforeground="black")
        self.Spinbox1_10.configure(textvariable=ga_gui_support.spinbox_function)
        self.value_list = ['MCCORMICK','MICHALEWICZ','SCHAFFERFUNCTION N.2',]
        self.Spinbox1_10.configure(values=self.value_list)

        self.Frame5 = tk.Frame(self.Frame2)
        self.Frame5.place(relx=0.021, rely=0.246, relheight=0.236
                , relwidth=0.958)
        self.Frame5.configure(relief='groove')
        self.Frame5.configure(borderwidth="1")
        self.Frame5.configure(relief="groove")
        self.Frame5.configure(background="#316060")
        self.Frame5.configure(highlightbackground="#d9d9d9")
        self.Frame5.configure(highlightcolor="black")

        self.Label8 = tk.Label(self.Frame5)
        self.Label8.place(relx=0.353, rely=0.008, height=28, width=160)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#316060")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(font="-family {Segoe UI} -size 12")
        self.Label8.configure(foreground="#fdfd00")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Environment''')

        self.Label9 = tk.Label(self.Frame5)
        self.Label9.place(relx=0.043, rely=0.213, height=28, width=160)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#316060")
        self.Label9.configure(borderwidth="0")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(font="-family {Segoe UI} -size 12")
        self.Label9.configure(foreground="#adf0f5")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(justify='left')
        self.Label9.configure(text='''epochs number :''')

        self.Label10 = tk.Label(self.Frame5)
        self.Label10.place(relx=0.044, rely=0.434, height=28, width=160)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#316060")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(font="-family {Segoe UI} -size 12")
        self.Label10.configure(foreground="#adf0f5")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''population size :''')

        self.Label11 = tk.Label(self.Frame5)
        self.Label11.place(relx=0.046, rely=0.664, height=28, width=160)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#316060")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(font="-family {Segoe UI} -size 12")
        self.Label11.configure(foreground="#adf0f5")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(justify='left')
        self.Label11.configure(text='''precision :''')
        tooltip_font = "TkDefaultFont"
        ToolTip(self.Label11, tooltip_font, '''precision :''', delay=0.5)

        self.Label12 = tk.Label(self.Frame5)
        self.Label12.place(relx=0.637, rely=0.164, height=28, width=121)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#316060")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(font="-family {Segoe UI} -size 12")
        self.Label12.configure(foreground="#adf0f5")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''optimization :''')

        self.Entry3 = tk.Entry(self.Frame5)
        self.Entry3.place(relx=0.33, rely=0.246,height=20, relwidth=0.194)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Entry4 = tk.Entry(self.Frame5)
        self.Entry4.place(relx=0.33, rely=0.467,height=20, relwidth=0.194)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")

        self.Entry5 = tk.Entry(self.Frame5)
        self.Entry5.place(relx=0.33, rely=0.689,height=20, relwidth=0.194)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Checkbutton1 = tk.Checkbutton(self.Frame5)
        self.Checkbutton1.place(relx=0.681, rely=0.377, relheight=0.262
                , relwidth=0.199)
        self.Checkbutton1.configure(activebackground="#316060")
        self.Checkbutton1.configure(activeforeground="#adf0f5")
        self.Checkbutton1.configure(background="#316060")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(font="-family {Segoe UI} -size 12")
        self.Checkbutton1.configure(foreground="#adf0f5")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''minimize''')
        self.Checkbutton1.configure(variable=ga_gui_support.che90)

        self.Checkbutton2 = tk.Checkbutton(self.Frame5)
        self.Checkbutton2.place(relx=0.681, rely=0.59, relheight=0.254
                , relwidth=0.199)
        self.Checkbutton2.configure(activebackground="#316060")
        self.Checkbutton2.configure(activeforeground="#adf0f5")
        self.Checkbutton2.configure(background="#316060")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(font="-family {Segoe UI} -size 12")
        self.Checkbutton2.configure(foreground="#adf0f5")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''maximize''')
        self.Checkbutton2.configure(variable=ga_gui_support.che91)

        self.Frame6 = tk.Frame(self.Frame2)
        self.Frame6.place(relx=0.021, rely=0.504, relheight=0.347
                , relwidth=0.958)
        self.Frame6.configure(relief='groove')
        self.Frame6.configure(borderwidth="1")
        self.Frame6.configure(relief="groove")
        self.Frame6.configure(background="#316060")
        self.Frame6.configure(highlightbackground="#d9d9d9")
        self.Frame6.configure(highlightcolor="black")

        self.Label13 = tk.Label(self.Frame6)
        self.Label13.place(relx=0.375, rely=0.006, height=44, width=147)
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(background="#316060")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(font="-family {Segoe UI} -size 12")
        self.Label13.configure(foreground="#fdfd00")
        self.Label13.configure(highlightbackground="#d9d9d9")
        self.Label13.configure(highlightcolor="black")
        self.Label13.configure(text='''Optimizer''')

        self.Label14 = tk.Label(self.Frame6)
        self.Label14.place(relx=0.022, rely=0.218, height=30, width=96)
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(background="#316060")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(font="-family {Segoe UI} -size 12")
        self.Label14.configure(foreground="#adf0f5")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''selection :''')

        self.Label14_3 = tk.Label(self.Frame6)
        self.Label14_3.place(relx=0.022, rely=0.385, height=30, width=96)
        self.Label14_3.configure(activebackground="#f9f9f9")
        self.Label14_3.configure(activeforeground="black")
        self.Label14_3.configure(background="#316060")
        self.Label14_3.configure(disabledforeground="#a3a3a3")
        self.Label14_3.configure(font="-family {Segoe UI} -size 12")
        self.Label14_3.configure(foreground="#adf0f5")
        self.Label14_3.configure(highlightbackground="#d9d9d9")
        self.Label14_3.configure(highlightcolor="black")
        self.Label14_3.configure(text='''crossover :''')

        self.Label14_4 = tk.Label(self.Frame6)
        self.Label14_4.place(relx=0.014, rely=0.553, height=30, width=108)
        self.Label14_4.configure(activebackground="#f9f9f9")
        self.Label14_4.configure(activeforeground="black")
        self.Label14_4.configure(background="#316060")
        self.Label14_4.configure(disabledforeground="#a3a3a3")
        self.Label14_4.configure(font="-family {Segoe UI} -size 12")
        self.Label14_4.configure(foreground="#adf0f5")
        self.Label14_4.configure(highlightbackground="#d9d9d9")
        self.Label14_4.configure(highlightcolor="black")
        self.Label14_4.configure(text='''mutation :''')

        self.Label14_5 = tk.Label(self.Frame6)
        self.Label14_5.place(relx=0.022, rely=0.737, height=30, width=147)
        self.Label14_5.configure(activebackground="#f9f9f9")
        self.Label14_5.configure(activeforeground="black")
        self.Label14_5.configure(background="#316060")
        self.Label14_5.configure(disabledforeground="#a3a3a3")
        self.Label14_5.configure(font="-family {Segoe UI} -size 12")
        self.Label14_5.configure(foreground="#adf0f5")
        self.Label14_5.configure(highlightbackground="#d9d9d9")
        self.Label14_5.configure(highlightcolor="black")
        self.Label14_5.configure(text='''inversion prob :''')

        self.Label14_6 = tk.Label(self.Frame6)
        self.Label14_6.place(relx=0.509, rely=0.218, height=30, width=70)
        self.Label14_6.configure(activebackground="#f9f9f9")
        self.Label14_6.configure(activeforeground="black")
        self.Label14_6.configure(background="#316060")
        self.Label14_6.configure(disabledforeground="#a3a3a3")
        self.Label14_6.configure(font="-family {Segoe UI} -size 12")
        self.Label14_6.configure(foreground="#adf0f5")
        self.Label14_6.configure(highlightbackground="#d9d9d9")
        self.Label14_6.configure(highlightcolor="black")
        self.Label14_6.configure(text='''param :''')

        self.Label14_7 = tk.Label(self.Frame6)
        self.Label14_7.place(relx=0.509, rely=0.553, height=30, width=70)
        self.Label14_7.configure(activebackground="#f9f9f9")
        self.Label14_7.configure(activeforeground="black")
        self.Label14_7.configure(background="#316060")
        self.Label14_7.configure(disabledforeground="#a3a3a3")
        self.Label14_7.configure(font="-family {Segoe UI} -size 12")
        self.Label14_7.configure(foreground="#adf0f5")
        self.Label14_7.configure(highlightbackground="#d9d9d9")
        self.Label14_7.configure(highlightcolor="black")
        self.Label14_7.configure(text='''param :''')

        self.Label14_8 = tk.Label(self.Frame6)
        self.Label14_8.place(relx=0.738, rely=0.737, height=30, width=70)
        self.Label14_8.configure(activebackground="#f9f9f9")
        self.Label14_8.configure(activeforeground="black")
        self.Label14_8.configure(background="#316060")
        self.Label14_8.configure(disabledforeground="#a3a3a3")
        self.Label14_8.configure(font="-family {Segoe UI} -size 12")
        self.Label14_8.configure(foreground="#adf0f5")
        self.Label14_8.configure(highlightbackground="#d9d9d9")
        self.Label14_8.configure(highlightcolor="black")
        self.Label14_8.configure(text='''rate :''')

        self.Spinbox1_11 = tk.Spinbox(self.Frame6, from_=1.0, to=100.0)
        self.Spinbox1_11.place(relx=0.198, rely=0.218, relheight=0.156
                , relwidth=0.298)
        self.Spinbox1_11.configure(activebackground="#f9f9f9")
        self.Spinbox1_11.configure(background="white")
        self.Spinbox1_11.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_11.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_11.configure(font="TkDefaultFont")
        self.Spinbox1_11.configure(foreground="black")
        self.Spinbox1_11.configure(highlightbackground="black")
        self.Spinbox1_11.configure(highlightcolor="black")
        self.Spinbox1_11.configure(insertbackground="black")
        self.Spinbox1_11.configure(selectbackground="#c4c4c4")
        self.Spinbox1_11.configure(selectforeground="black")
        self.Spinbox1_11.configure(textvariable=ga_gui_support.spinbox_selection)
        self.value_list = ['truncation','randomK','roulette', 'tournament']
        self.Spinbox1_11.configure(values=self.value_list)

        self.Spinbox1_12 = tk.Spinbox(self.Frame6, from_=1.0, to=100.0)
        self.Spinbox1_12.place(relx=0.198, rely=0.402, relheight=0.151
                , relwidth=0.298)
        self.Spinbox1_12.configure(activebackground="#f9f9f9")
        self.Spinbox1_12.configure(background="white")
        self.Spinbox1_12.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_12.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_12.configure(font="TkDefaultFont")
        self.Spinbox1_12.configure(foreground="black")
        self.Spinbox1_12.configure(highlightbackground="black")
        self.Spinbox1_12.configure(highlightcolor="black")
        self.Spinbox1_12.configure(insertbackground="black")
        self.Spinbox1_12.configure(selectbackground="#c4c4c4")
        self.Spinbox1_12.configure(selectforeground="black")
        self.Spinbox1_12.configure(textvariable=ga_gui_support.spinbox_crossover)
        self.value_list = ['one-point','two-point','three-point', 'united']
        self.Spinbox1_12.configure(values=self.value_list)

        self.Spinbox1_1 = tk.Spinbox(self.Frame6, from_=1.0, to=100.0)
        self.Spinbox1_1.place(relx=0.198, rely=0.581, relheight=0.156
                , relwidth=0.298)
        self.Spinbox1_1.configure(activebackground="#f9f9f9")
        self.Spinbox1_1.configure(background="white")
        self.Spinbox1_1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_1.configure(font="TkDefaultFont")
        self.Spinbox1_1.configure(foreground="black")
        self.Spinbox1_1.configure(highlightbackground="black")
        self.Spinbox1_1.configure(highlightcolor="black")
        self.Spinbox1_1.configure(insertbackground="black")
        self.Spinbox1_1.configure(selectbackground="#c4c4c4")
        self.Spinbox1_1.configure(selectforeground="black")
        self.Spinbox1_1.configure(textvariable=ga_gui_support.spinbox_mutation)
        self.value_list = ['edge','any']
        self.Spinbox1_1.configure(values=self.value_list)

        self.Entry6 = tk.Entry(self.Frame6)
        self.Entry6.place(relx=0.278, rely=0.76,height=20, relwidth=0.075)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")

        self.Entry7 = tk.Entry(self.Frame6)
        self.Entry7.place(relx=0.637, rely=0.257,height=20, relwidth=0.075)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")

        self.Entry7_10 = tk.Entry(self.Frame6)
        self.Entry7_10.place(relx=0.637, rely=0.581,height=20, relwidth=0.075)
        self.Entry7_10.configure(background="white")
        self.Entry7_10.configure(disabledforeground="#a3a3a3")
        self.Entry7_10.configure(font="TkFixedFont")
        self.Entry7_10.configure(foreground="#000000")
        self.Entry7_10.configure(highlightbackground="#d9d9d9")
        self.Entry7_10.configure(highlightcolor="black")
        self.Entry7_10.configure(insertbackground="black")
        self.Entry7_10.configure(selectbackground="#c4c4c4")
        self.Entry7_10.configure(selectforeground="black")

        self.Label14_9 = tk.Label(self.Frame6)
        self.Label14_9.place(relx=0.734, rely=0.553, height=30, width=70)
        self.Label14_9.configure(activebackground="#f9f9f9")
        self.Label14_9.configure(activeforeground="black")
        self.Label14_9.configure(background="#316060")
        self.Label14_9.configure(disabledforeground="#a3a3a3")
        self.Label14_9.configure(font="-family {Segoe UI} -size 12")
        self.Label14_9.configure(foreground="#adf0f5")
        self.Label14_9.configure(highlightbackground="#d9d9d9")
        self.Label14_9.configure(highlightcolor="black")
        self.Label14_9.configure(text='''prob :''')

        self.Entry6_11 = tk.Entry(self.Frame6)
        self.Entry6_11.place(relx=0.857, rely=0.425,height=20, relwidth=0.075)
        self.Entry6_11.configure(background="white")
        self.Entry6_11.configure(disabledforeground="#a3a3a3")
        self.Entry6_11.configure(font="TkFixedFont")
        self.Entry6_11.configure(foreground="#000000")
        self.Entry6_11.configure(highlightbackground="#d9d9d9")
        self.Entry6_11.configure(highlightcolor="black")
        self.Entry6_11.configure(insertbackground="black")
        self.Entry6_11.configure(selectbackground="#c4c4c4")
        self.Entry6_11.configure(selectforeground="black")

        self.Entry6_12 = tk.Entry(self.Frame6)
        self.Entry6_12.place(relx=0.857, rely=0.581,height=20, relwidth=0.075)
        self.Entry6_12.configure(background="white")
        self.Entry6_12.configure(disabledforeground="#a3a3a3")
        self.Entry6_12.configure(font="TkFixedFont")
        self.Entry6_12.configure(foreground="#000000")
        self.Entry6_12.configure(highlightbackground="#d9d9d9")
        self.Entry6_12.configure(highlightcolor="black")
        self.Entry6_12.configure(insertbackground="black")
        self.Entry6_12.configure(selectbackground="#c4c4c4")
        self.Entry6_12.configure(selectforeground="black")

        self.Entry6_2 = tk.Entry(self.Frame6)
        self.Entry6_2.place(relx=0.857, rely=0.749,height=20, relwidth=0.075)
        self.Entry6_2.configure(background="white")
        self.Entry6_2.configure(disabledforeground="#a3a3a3")
        self.Entry6_2.configure(font="TkFixedFont")
        self.Entry6_2.configure(foreground="#000000")
        self.Entry6_2.configure(highlightbackground="#d9d9d9")
        self.Entry6_2.configure(highlightcolor="black")
        self.Entry6_2.configure(insertbackground="black")
        self.Entry6_2.configure(selectbackground="#c4c4c4")
        self.Entry6_2.configure(selectforeground="black")

        self.Checkbutton3 = tk.Checkbutton(self.Frame6)
        self.Checkbutton3.place(relx=0.571, rely=0.737, relheight=0.156
                , relwidth=0.158)
        self.Checkbutton3.configure(activebackground="#316060")
        self.Checkbutton3.configure(activeforeground="#adf0f5")
        self.Checkbutton3.configure(background="#316060")
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(font="-family {Segoe UI} -size 12")
        self.Checkbutton3.configure(foreground="#adf0f5")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify='left')
        self.Checkbutton3.configure(text='''elitism''')
        self.Checkbutton3.configure(variable=ga_gui_support.che120)

        self.Label14_10 = tk.Label(self.Frame6)
        self.Label14_10.place(relx=0.734, rely=0.385, height=30, width=70)
        self.Label14_10.configure(activebackground="#f9f9f9")
        self.Label14_10.configure(activeforeground="black")
        self.Label14_10.configure(background="#316060")
        self.Label14_10.configure(disabledforeground="#a3a3a3")
        self.Label14_10.configure(font="-family {Segoe UI} -size 12")
        self.Label14_10.configure(foreground="#adf0f5")
        self.Label14_10.configure(highlightbackground="#d9d9d9")
        self.Label14_10.configure(highlightcolor="black")
        self.Label14_10.configure(text='''prob :''')

        self.Button1 = tk.Button(self.Frame2)
        self.Button1.place(relx=0.653, rely=0.888, height=44, width=157)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(borderwidth="4")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button1.configure(foreground="#690f96")
        self.Button1.configure(highlightbackground="#8080c0")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''RUN''')
        self.Button1.bind('<Button-1>',lambda e:ga_gui_support.run(e))

        self.Frame3 = tk.Frame(self.Frame1)
        self.Frame3.place(relx=0.503, rely=0.117, relheight=0.864
                , relwidth=0.484)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#595959")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")

        self.Frame7 = tk.Frame(self.Frame3)
        self.Frame7.place(relx=0.016, rely=0.021, relheight=0.328
                , relwidth=0.964)
        self.Frame7.configure(relief='groove')
        self.Frame7.configure(borderwidth="2")
        self.Frame7.configure(relief="groove")
        self.Frame7.configure(background="#376c6c")
        self.Frame7.configure(highlightbackground="#d9d9d9")
        self.Frame7.configure(highlightcolor="black")

        self.Frame8 = tk.Frame(self.Frame7)
        self.Frame8.place(relx=0.022, rely=0.071, relheight=0.172
                , relwidth=0.956)
        self.Frame8.configure(relief="groove")
        self.Frame8.configure(background="#ffffff")
        self.Frame8.configure(highlightbackground="#d9d9d9")
        self.Frame8.configure(highlightcolor="black")

        self.Label15 = tk.Label(self.Frame8)
        self.Label15.place(relx=0.01, rely=0.0, height=25, anchor=tk.NW)
        self.Label15.configure(activebackground="#ffffff")
        self.Label15.configure(activeforeground="black")
        self.Label15.configure(background="#ffffff")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(font="-family {Segoe UI} -size 12")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(highlightbackground="#d9d9d9")
        self.Label15.configure(highlightcolor="black")
        self.Label15.configure(text='''computation time :''')
        self.Label15.configure(justify=tk.LEFT)

        self.Label15_13 = tk.Label(self.Frame8)
        self.Label15_13.place(rely=0, relx=0.54, height=24, width=300)
        self.Label15_13.configure(activebackground="#ffffff")
        self.Label15_13.configure(activeforeground="black")
        self.Label15_13.configure(background="white")
        self.Label15_13.configure(disabledforeground="#a3a3a3")
        self.Label15_13.configure(font="-family {Segoe UI} -size 12")
        self.Label15_13.configure(foreground="#000000")
        self.Label15_13.configure(highlightbackground="#d9d9d9")
        self.Label15_13.configure(highlightcolor="black")

        self.Frame8_12 = tk.Frame(self.Frame7)
        self.Frame8_12.place(relx=0.022, rely=0.296, relheight=0.178
                , relwidth=0.956)
        self.Frame8_12.configure(relief="groove")
        self.Frame8_12.configure(background="#ffffff")
        self.Frame8_12.configure(highlightbackground="#d9d9d9")
        self.Frame8_12.configure(highlightcolor="black")

        self.Label15_3 = tk.Label(self.Frame8_12)
        self.Label15_3.place(relx=0.01, rely=0.033, height=25, anchor=tk.NW)
        self.Label15_3.configure(activebackground="#f9f9f9")
        self.Label15_3.configure(activeforeground="black")
        self.Label15_3.configure(background="#ffffff")
        self.Label15_3.configure(disabledforeground="#a3a3a3")
        self.Label15_3.configure(font="-family {Segoe UI} -size 12")
        self.Label15_3.configure(foreground="#000000")
        self.Label15_3.configure(highlightbackground="#d9d9d9")
        self.Label15_3.configure(highlightcolor="black")
        self.Label15_3.configure(text='''solution :''')
        self.Label15_3.configure(justify=tk.LEFT)

        self.Label15_14 = tk.Label(self.Frame8_12)
        self.Label15_14.place(relx=0.22, rely=0.0, height=25, width=450)
        self.Label15_14.configure(activebackground="#ffffff")
        self.Label15_14.configure(activeforeground="black")
        self.Label15_14.configure(background="white")
        self.Label15_14.configure(disabledforeground="#a3a3a3")
        self.Label15_14.configure(font="-family {Segoe UI} -size 12")
        self.Label15_14.configure(foreground="#000000")
        self.Label15_14.configure(highlightbackground="#d9d9d9")
        self.Label15_14.configure(highlightcolor="black")

        self.Frame8_13 = tk.Frame(self.Frame7)
        self.Frame8_13.place(relx=0.022, rely=0.527, relheight=0.178
                , relwidth=0.956)
        self.Frame8_13.configure(relief="groove")
        self.Frame8_13.configure(background="#ffffff")
        self.Frame8_13.configure(highlightbackground="#d9d9d9")
        self.Frame8_13.configure(highlightcolor="black")

        self.Label15_4 = tk.Label(self.Frame8_13)
        self.Label15_4.place(relx=0.01, rely=0.033, height=25, anchor=tk.NW)
        self.Label15_4.configure(activebackground="#f9f9f9")
        self.Label15_4.configure(activeforeground="black")
        self.Label15_4.configure(background="#ffffff")
        self.Label15_4.configure(disabledforeground="#a3a3a3")
        self.Label15_4.configure(font="-family {Segoe UI} -size 12")
        self.Label15_4.configure(foreground="#000000")
        self.Label15_4.configure(highlightbackground="#d9d9d9")
        self.Label15_4.configure(highlightcolor="black")
        self.Label15_4.configure(text='''mean +/- std:''')
        self.Label15_4.configure(justify=tk.LEFT)

        self.Label15_15 = tk.Label(self.Frame8_13)
        self.Label15_15.place(relx=0.35, rely=0.0, height=25, width=350)
        self.Label15_15.configure(activebackground="#ffffff")
        self.Label15_15.configure(activeforeground="black")
        self.Label15_15.configure(background="white")
        self.Label15_15.configure(disabledforeground="#a3a3a3")
        self.Label15_15.configure(font="-family {Segoe UI} -size 12")
        self.Label15_15.configure(foreground="#000000")
        self.Label15_15.configure(highlightbackground="#d9d9d9")
        self.Label15_15.configure(highlightcolor="black")
        self.Label15_15.configure(anchor=tk.NE)


        self.Frame8_5 = tk.Frame(self.Frame7)
        self.Frame8_5.place(relx=0.022, rely=0.763, relheight=0.172
                , relwidth=0.956)
        self.Frame8_5.configure(relief="groove")
        self.Frame8_5.configure(background="#ffffff")
        self.Frame8_5.configure(highlightbackground="#d9d9d9")
        self.Frame8_5.configure(highlightcolor="black")

        self.Label15_6 = tk.Label(self.Frame8_5)
        self.Label15_6.place(relx=0.01, rely=0, height=25, anchor=tk.NW)
        self.Label15_6.configure(activebackground="#f9f9f9")
        self.Label15_6.configure(activeforeground="black")
        self.Label15_6.configure(background="#ffffff")
        self.Label15_6.configure(disabledforeground="#a3a3a3")
        self.Label15_6.configure(font="-family {Segoe UI} -size 12")
        self.Label15_6.configure(foreground="#000000")
        self.Label15_6.configure(highlightbackground="#d9d9d9")
        self.Label15_6.configure(highlightcolor="black")
        self.Label15_6.configure(text='''mae :''')
        self.Label15_6.configure(justify=tk.RIGHT)

        self.Label15_7 = tk.Label(self.Frame8_5)
        self.Label15_7.place(relx=0.575, rely=0.0, height=24, width=300)
        self.Label15_7.configure(activebackground="#ffffff")
        self.Label15_7.configure(activeforeground="black")
        self.Label15_7.configure(background="white")
        self.Label15_7.configure(disabledforeground="#a3a3a3")
        self.Label15_7.configure(font="-family {Segoe UI} -size 12")
        self.Label15_7.configure(foreground="#000000")
        self.Label15_7.configure(highlightbackground="#d9d9d9")
        self.Label15_7.configure(highlightcolor="black")
        self.Label15_7.configure(highlightcolor="black")

        self.Frame9 = tk.Frame(self.Frame3)
        self.Frame9.place(relx=0.021, rely=0.368, relheight=0.612
                , relwidth=0.957)
        self.Frame9.configure(relief='groove')
        self.Frame9.configure(borderwidth="1")
        self.Frame9.configure(relief="groove")
        self.Frame9.configure(background="#ffffff")
        self.Frame9.configure(highlightbackground="#d9d9d9")
        self.Frame9.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(self.Frame9)
        self.Canvas1.place(relx=-0.017, rely=-0.028, relheight=1.047
                , relwidth=1.021)
        self.Canvas1.configure(background="#ffffff")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.01, rely=0.039, height=36, width=614)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#376c6c")
        self.Label2.configure(borderwidth="1")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label2.configure(foreground="#d7d7d7")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(relief="groove")
        self.Label2.configure(text='''Configuration''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.503, rely=0.039, height=36, width=611)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#376c6c")
        self.Label3.configure(borderwidth="1")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label3.configure(foreground="#d7d7d7")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(relief="groove")
        self.Label3.configure(text='''Results''')

# ======================================================
# Modified by Rozen to remove Tkinter import statements and to receive
# the font as an argument.
# ======================================================
# Found the original code at:
# http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
# ======================================================

from time import time, localtime, strftime

class ToolTip(tk.Toplevel):
    """
    Provides a ToolTip widget for Tkinter.
    To apply a ToolTip to any Tkinter widget, simply pass the widget to the
    ToolTip constructor
    """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=1, follow=True):
        """
        Initialize the ToolTip

        Arguments:
          wdgt: The widget this ToolTip is assigned to
          tooltip_font: Font to be used
          msg:  A static string message assigned to the ToolTip
          msgFunc: A function that retrieves a string to use as the ToolTip text
          delay:   The delay in seconds before the ToolTip appears(may be float)
          follow:  If True, the ToolTip follows motion, otherwise hides
        """
        self.wdgt = wdgt
        # The parent of the ToolTip is the parent of the ToolTips widget
        self.parent = self.wdgt.master
        # Initalise the Toplevel
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        # Hide initially
        self.withdraw()
        # The ToolTip Toplevel should have no frame or title bar
        self.overrideredirect(True)

        # The msgVar will contain the text displayed by the ToolTip
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        # The text of the ToolTip is displayed in a Message widget
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()

        # Add bindings to the widget.  This will NOT override
        # bindings that the widget already has
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')

    def spawn(self, event=None):
        """
        Spawn the ToolTip.  This simply makes the ToolTip eligible for display.
        Usually this is caused by entering the widget

        Arguments:
          event: The event that called this funciton
        """
        self.visible = 1
        # The after function takes a time argument in miliseconds
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        """
        Displays the ToolTip if the time delay has been long enough
        """
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        """
        Processes motion within the widget.
        Arguments:
          event: The event that called this function
        """
        self.lastMotion = time()
        # If the follow flag is not set, motion within the
        # widget will make the ToolTip disappear
        #
        if self.follow is False:
            self.withdraw()
            self.visible = 1

        # Offset the ToolTip 10x10 pixes southwest of the pointer
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            # Try to call the message function.  Will not change
            # the message if the message function is None or
            # the message function fails
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        """
        Hides the ToolTip.  Usually this is caused by leaving the widget
        Arguments:
          event: The event that called this function
        """
        self.visible = 0
        self.withdraw()

# ===========================================================
#                   End of Class ToolTip
# ===========================================================

if __name__ == '__main__':
    vp_start_gui()





